// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXiqquN1EczYdz4LDdPqE2KTkn2-YVP74',
    appId: '1:252105781057:web:90a4ac7d873e635acffbc0',
    messagingSenderId: '252105781057',
    projectId: 'mlisflutterbasic',
    authDomain: 'mlisflutterbasic.firebaseapp.com',
    storageBucket: 'mlisflutterbasic.appspot.com',
    measurementId: 'G-9NVMKW355Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBif29K1gHH_YNmkt1HVuvyWzSQTc17EAg',
    appId: '1:252105781057:android:4b0e36ffed770260cffbc0',
    messagingSenderId: '252105781057',
    projectId: 'mlisflutterbasic',
    storageBucket: 'mlisflutterbasic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9kdhKBETJgcwQhOCzsqf9qTjuBMCW1ys',
    appId: '1:252105781057:ios:e313ff954dd9c8aecffbc0',
    messagingSenderId: '252105781057',
    projectId: 'mlisflutterbasic',
    storageBucket: 'mlisflutterbasic.appspot.com',
    androidClientId: '252105781057-0941n15qb2m4d6jsg26b0na7md46hjc7.apps.googleusercontent.com',
    iosClientId: '252105781057-2rstpvp0p4bqlp2vikjsnimt53pm8bvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9kdhKBETJgcwQhOCzsqf9qTjuBMCW1ys',
    appId: '1:252105781057:ios:e313ff954dd9c8aecffbc0',
    messagingSenderId: '252105781057',
    projectId: 'mlisflutterbasic',
    storageBucket: 'mlisflutterbasic.appspot.com',
    androidClientId: '252105781057-0941n15qb2m4d6jsg26b0na7md46hjc7.apps.googleusercontent.com',
    iosClientId: '252105781057-2rstpvp0p4bqlp2vikjsnimt53pm8bvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXiqquN1EczYdz4LDdPqE2KTkn2-YVP74',
    appId: '1:252105781057:web:75f3f1d99487157dcffbc0',
    messagingSenderId: '252105781057',
    projectId: 'mlisflutterbasic',
    authDomain: 'mlisflutterbasic.firebaseapp.com',
    storageBucket: 'mlisflutterbasic.appspot.com',
    measurementId: 'G-4H4MENZ73P',
  );
}
